on: [push, pull_request]
jobs:
  ci:
    name: CI
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: 'Install Go'
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: 'Bundle Zip'
      if: github.repository == 'CrunchyData/pg_eventserv' && github.ref_name == 'main'
      env:
        MATRIX_OS: ${{ matrix.os }}
        PROGRAM: pg_eventserv
      run: ./ci/github-bundle.sh
      shell: bash

    - name: 'Login to AWS'
      if: github.repository == 'CrunchyData/pg_eventserv' && github.ref_name == 'main'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: 'Upload Zip'
      if: github.repository == 'CrunchyData/pg_eventserv' && github.ref_name == 'main'
      run: aws s3 sync ./upload s3://postgisftw
